import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import clsx from "clsx";
import NextTopLoader from "nextjs-toploader";
import Navbar from "./components/Navbar";
import { Theme } from '@radix-ui/themes'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const POPPINS_FONT = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Poppins-Thin.ttf",
      weight: "50",
      style: "thin",
    },

    {
      path: "../../public/assets/fonts/Poppins-ExtraLight.ttf",
      weight: "100",
      style: "extralight",
    },

    {
      path: "../../public/assets/fonts/Poppins-Light.ttf",
      weight: "200",
      style: "light",
    },

    {
      path: "../../public/assets/fonts/Poppins-Regular.ttf",
      weight: "300",
      style: "normal",
    },

    {
      path: "../../public/assets/fonts/Poppins-Medium.ttf",
      weight: "400",
      style: "medium",
    },
    {
      path: "../../public/assets/fonts/Poppins-Black.ttf",
      weight: "500",
      style: "black",
    },

    {
      path: "../../public/assets/fonts/Poppins-Bold.ttf",
      weight: "600",
      style: "bold",
    },

    {
      path: "../../public/assets/fonts/Poppins-SemiBold.ttf",
      weight: "700",
      style: "semiBold",
    },

    {
      path: "../../public/assets/fonts/Poppins-ExtraBold.ttf",
      weight: "800",
      style: "extraBold",
    },
  ],
  display: "swap",
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(POPPINS_FONT.variable, "font-primary bg-secondary-300")}>
        <NextTopLoader color="#9933FF" />
        <Navbar />
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
